#!/bin/bash

MAIN_DOTFILES_DIR="$HOME/.dotfiles"

# 1. Клонируем или обновляем основной репозиторий dotfiles
if [ ! -d "$MAIN_DOTFILES_DIR" ]; then
    git clone https://github.com/zimkaa/.dotfiles.git "$MAIN_DOTFILES_DIR"
else
    git -C "$MAIN_DOTFILES_DIR" pull
fi

# 2. Линкуем Neovim и остальное из свежевыкачанного репозитория
export XDG_CONFIG_HOME="$HOME"/.config
mkdir -p "$XDG_CONFIG_HOME"

ln -sfn "$MAIN_DOTFILES_DIR/.config" "$XDG_CONFIG_HOME"
ln -sf "$MAIN_DOTFILES_DIR/.zshrc" "$HOME/.zshrc"
ln -sf "$MAIN_DOTFILES_DIR/.vimrc" "$HOME/.vimrc"

git clone https://github.com/tmux-plugins/tpm "$HOME/.tmux/plugins/tpm"
